04:35:00 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:08 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:13 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:19 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:25 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:31 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:37 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:43 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:48 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:35:54 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:00 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:06 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:12 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:18 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:24 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:30 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:35 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:41 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:47 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:53 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:36:59 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:05 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:10 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:16 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:22 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:28 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:35 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:42 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:48 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:37:54 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:00 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:06 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:12 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:18 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:25 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:37 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:44 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:49 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:38:55 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:01 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:07 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:13 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:19 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:25 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:32 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:39 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:47 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:39:53 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:01 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:08 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:15 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:21 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:29 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:36 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:42 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:52 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:40:59 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:08 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:15 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:26 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:33 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:41 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:48 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:41:55 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:08 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:14 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:22 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:31 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:38 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:45 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:51 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:42:57 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:03 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:09 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:14 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:20 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:26 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:33 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:39 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:45 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:52 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:43:59 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:07 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:14 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:21 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:28 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:36 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:43 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:50 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:44:58 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:45:05 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:45:12 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
04:45:20 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
11:50:16 CRITICAL [                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 131, in runCouchPotato
    os.remove(os.path.join(backup_path, eb[1]))
OSError: [Errno 2] No such file or directory: '/config/data/db_backup/1548931580.tar.gz'
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 131, in runCouchPotato
    os.remove(os.path.join(backup_path, eb[1]))
OSError: [Errno 2] No such file or directory: '/config/data/db_backup/1548931580.tar.gz'
06:12:19 CRITICAL [                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 131, in runCouchPotato
    os.remove(os.path.join(backup_path, eb[1]))
OSError: [Errno 2] No such file or directory: '/config/data/db_backup/1549657784.tar.gz'
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 131, in runCouchPotato
    os.remove(os.path.join(backup_path, eb[1]))
OSError: [Errno 2] No such file or directory: '/config/data/db_backup/1549657784.tar.gz'
03:31:30 CRITICAL [                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 131, in runCouchPotato
    os.remove(os.path.join(backup_path, eb[1]))
OSError: [Errno 2] No such file or directory: '/config/data/db_backup/1553605883.tar.gz'
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 131, in runCouchPotato
    os.remove(os.path.join(backup_path, eb[1]))
OSError: [Errno 2] No such file or directory: '/config/data/db_backup/1553605883.tar.gz'
03:31:36 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:31:42 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:31:48 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:31:53 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:31:59 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:05 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:10 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:16 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:22 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:27 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:33 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:39 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:44 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
03:32:54 CRITICAL [31m[                 __main__] Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
[0m
Traceback (most recent call last):
  File "/app/couchpotato/CouchPotato.py", line 135, in <module>
    l.run()
  File "/app/couchpotato/CouchPotato.py", line 89, in run
    runCouchPotato(self.options, base_path, sys.argv[1:], data_dir = self.data_dir, log_dir = self.log_dir, Env = Env)
  File "/app/couchpotato/couchpotato/runner.py", line 353, in runCouchPotato
    server.listen(config['port'], config['host'])
  File "/app/couchpotato/libs/tornado/tcpserver.py", line 125, in listen
    sockets = bind_sockets(port, address=address)
  File "/app/couchpotato/libs/tornado/netutil.py", line 145, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address in use
